spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=${PORT:8080}

# HEALTH ENDPOINT
management.endpoint.health.show-details=always

access.control.allow.origin=${CORS_ORIGIN:*}
access.control.allow.methods=POST, PUT, GET, OPTIONS, DELETE
access.control.allow.headers=Authorization, Content-Type
access.control.max.age=3600

app.upload.root=${APP_UPLOAD_ROOT:D:/DATN/eo-be/data}
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
