# HEALTH ENDPOINT
management.endpoint.health.show-details=always

access.control.allow.origin=*
access.control.allow.methods=POST, PUT, GET, OPTIONS, DELETE
access.control.allow.headers=Authorization, Content-Type
access.control.max.age=3600

app.upload.root=D:/DATN/eo-be/data
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
